name: Build Full Stack (Whyred)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make bc bison flex \
            libssl-dev qemu-user-static debos curl git \
            libgnutls28-dev

      - name: Build Kernel
        run: |
          rm -rf linux
          git clone --depth=1 --branch qcom-sdm660-6.15.y https://github.com/sdm660-mainline/linux.git
          cd linux
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make sdm660_defconfig
          make -j$(nproc)

      - name: Build U-Boot
        run: |
          rm -rf u-boot
          git clone --depth=1 https://github.com/u-boot/u-boot.git u-boot
          cd u-boot
          export CROSS_COMPILE=aarch64-linux-gnu-
          make qcom_defconfig
          make -j$(nproc)

      - name: Prepare Kernel Output
        run: |
          mkdir -p out
          cp linux/arch/arm64/boot/Image out/
          cp linux/arch/arm64/boot/dts/qcom/whyred.dtb out/

      - name: Prepare Mobian Recipes and Image YAML
        run: |
          rm -rf mobian-recipes
          git clone --depth=1 https://salsa.debian.org/Mobian-team/mobian-recipes.git
          mkdir -p mobian-recipes/devices/whyred/
          echo "actions:" > mobian-recipes/devices/whyred/image.yaml
          echo "  - action: unpack" >> mobian-recipes/devices/whyred/image.yaml
          echo "    description: Copy kernel" >> mobian-recipes/devices/whyred/image.yaml
          echo "    file: ../../out/Image" >> mobian-recipes/devices/whyred/image.yaml
          echo "    source: plain" >> mobian-recipes/devices/whyred/image.yaml
          echo "    compression: none" >> mobian-recipes/devices/whyred/image.yaml
          echo "  - action: unpack" >> mobian-recipes/devices/whyred/image.yaml
          echo "    description: Copy DTB" >> mobian-recipes/devices/whyred/image.yaml
          echo "    file: ../../out/whyred.dtb" >> mobian-recipes/devices/whyred/image.yaml
          echo "    source: plain" >> mobian-recipes/devices/whyred/image.yaml
          echo "    compression: none" >> mobian-recipes/devices/whyred/image.yaml
          echo "  - action: run" >> mobian-recipes/devices/whyred/image.yaml
          echo "    script: |" >> mobian-recipes/devices/whyred/image.yaml
          echo "      mkdir -p /etc" >> mobian-recipes/devices/whyred/image.yaml
          echo "      echo 'nameserver 1.1.1.1' > /etc/resolv.conf" >> mobian-recipes/devices/whyred/image.yaml
          echo "    chroot: false" >> mobian-recipes/devices/whyred/image.yaml
          echo "  - action: debootstrap" >> mobian-recipes/devices/whyred/image.yaml
          echo "    suite: bookworm" >> mobian-recipes/devices/whyred/image.yaml
          echo "    components:" >> mobian-recipes/devices/whyred/image.yaml
          echo "      - main" >> mobian-recipes/devices/whyred/image.yaml
          echo "    mirror: http://deb.debian.org/debian" >> mobian-recipes/devices/whyred/image.yaml
          echo "    variant: minbase" >> mobian-recipes/devices/whyred/image.yaml
          echo "    keyring-package: debian-archive-keyring" >> mobian-recipes/devices/whyred/image.yaml
          echo "  - action: overlay" >> mobian-recipes/devices/whyred/image.yaml
          echo "    source: overlay" >> mobian-recipes/devices/whyred/image.yaml
          echo "  - action: pack" >> mobian-recipes/devices/whyred/image.yaml
          echo "    description: Create rootfs image" >> mobian-recipes/devices/whyred/image.yaml
          echo "    file: whyred-rootfs.img" >> mobian-recipes/devices/whyred/image.yaml
          echo "    format: ext4" >> mobian-recipes/devices/whyred/image.yaml
          echo "    size: 2GB" >> mobian-recipes/devices/whyred/image.yaml

      - name: Build RootFS with Debos
        run: |
          sudo apt update
          sudo apt install -y debos qemu-user-static
          debos -m aarch64 mobian-recipes/devices/whyred/image.yaml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/*.img
            **/*.bin
