name: Build Full Stack (Whyred)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make bc bison flex \
                              libssl-dev qemu-user-static debos curl git

      - name: Clone and Build Kernel
        run: |
         rm -rf linux
         git clone --depth=1 --branch qcom-sdm660-6.15.y https://github.com/sdm660-mainline/linux.git
         cd linux
         export ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
         make sdm660_defconfig
         make -j$(nproc)

      - name: Install U-Boot dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y libgnutls28-dev

      - name: Build U-Boot
        run: |
         rm -rf u-boot
         git clone --depth=1 https://github.com/u-boot/u-boot.git u-boot
         cd u-boot
         export CROSS_COMPILE=aarch64-linux-gnu-
         make qcom_defconfig
         make -j$(nproc)
         
      - name: Build lk2nd
        run: |
         rm -rf lk2nd
         git clone --depth=1 https://github.com/sdm660-mainline/lk2nd.git
         cd lk2nd
         printf "PROJECT := msm8953/whyred\nARCH := arm64\nCROSS_COMPILE := aarch64-linux-gnu-\n" > local.mk
         make -j$(nproc)


      - name: Build RootFS with Debos (Whyred)
        run: |
         rm -rf mobian-recipes
         git clone --depth=1 https://salsa.debian.org/Mobian-team/mobian-recipes.git
         cd mobian-recipes
         debos -m aarch64 devices/whyred/image.yaml


      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/*.img
            **/*.bin
